---
title: "HMDA Data Basics"
author: "Antonio Solorio, Economist II - Nevada Department of Employment Training and Rehabilitation"
date: "2024-05-03"
output: html_document
---

# Introduction to The Home Mortgage Disclosure Act

The Home Mortgage Disclosure Act (HMDA) Data refers to the information collected under the provisions of the Home Mortgage Disclosure Act of 1975. This Act was created with the purpose of ensuring fair lending practices and to help public officials in determining whether financial institutions are serving the housing needs of their communities. Additionally, HMDA data aids in identifying possible discriminatory lending patterns and enforcing anti-discrimination statutes.

Financial institutions such as banks, savings associations, credit unions, and other mortgage lending institutions are required to report this data if they meet certain criteria that typically involve asset size, location, and the number of home loans originated. For more information on what entities and transaction types are required to collect and report HMDA data, visit [https://www.consumerfinance.gov/rules-policy/regulations/1003/1/](https://www.consumerfinance.gov/rules-policy/regulations/1003/1/).

The data gathered encompasses a wide range of detailed information pertaining to home loan applications. This includes the race, ethnicity, and income of the applicants, as well as the loan amount requested, the kind of loan, and its purpose (such as purchase, refinance, or home improvement), and other details of the loan transaction.

# Accesing HMDA Data

HMDA data is made available to the public by law, but is modified slightly to protect applicant and borrower privacy. The data can be found at [https://www.consumerfinance.gov/data-research/hmda/](https://www.consumerfinance.gov/data-research/hmda/). It is important to know that the type of data reported and made available to the public has changed over time, while data is available going as far back as 2007, not all data points are reported/published for all years. For example property values were not included in public datasets until 

